import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <div className="flex min-h-screen">
          <aside className="hidden md:flex flex-col w-72 bg-[#8b1538] text-white p-6">
            <div className="flex items-center gap-3 mb-6">
              <div className="h-10 w-10 rounded-full bg-white/10 flex items-center justify-center font-semibold">BH</div>
              <div className="text-lg font-semibold">BYUH Assistant</div>
            </div>
            <nav className="flex-1">
              <button className="w-full bg-white/10 hover:bg-white/20 rounded-md py-2 px-3 text-left">+ New chat</button>
            </nav>
          </aside>
          <main className="flex-1 bg-zinc-50 dark:bg-black">{children}</main>
        </div>
      </body>
    </html>
  );
}
